#if 0
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Note: shader requires additional functionality:
//       Typed UAV Load Additional Formats
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_1
dcl_globalFlags refactoringAllowed | allResourcesBound
dcl_constantbuffer CB0[0:0][1], immediateIndexed, space=0
dcl_uav_typed_texture2d (float,float,float,float) U0[0:0], space=0
dcl_input vThreadID.xy
dcl_temps 1
dcl_thread_group 8, 8, 1
uge r0.xy, vThreadID.xyxx, CB0[0][0].xyxx
or r0.x, r0.y, r0.x
if_nz r0.x
  ret 
endif 
ld_uav_typed r0.xyzw, vThreadID.xyyy, U0[0].xyzw
mov_sat r0.w, r0.w
store_uav_typed U0[0].xyzw, vThreadID.xyyy, r0.xyzw
ret 
// Approximately 0 instruction slots used
#endif

const BYTE alpha_clamp_cs[] =
{
     68,  88,  66,  67,  72, 189, 
     53, 234, 120, 151,   4, 143, 
     42,  58, 202, 250,  74, 150, 
     92, 227,   1,   0,   0,   0, 
    108,   1,   0,   0,   4,   0, 
      0,   0,  48,   0,   0,   0, 
     64,   0,   0,   0,  80,   0, 
      0,   0,  92,   1,   0,   0, 
     73,  83,  71,  78,   8,   0, 
      0,   0,   0,   0,   0,   0, 
      8,   0,   0,   0,  79,  83, 
     71,  78,   8,   0,   0,   0, 
      0,   0,   0,   0,   8,   0, 
      0,   0,  83,  72,  69,  88, 
      4,   1,   0,   0,  81,   0, 
      5,   0,  65,   0,   0,   0, 
    106,   8,   8,   1,  89,   0, 
      0,   7,  70, 142,  48,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      1,   0,   0,   0,   0,   0, 
      0,   0, 156,  24,   0,   7, 
     70, 238,  49,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,  85,  85, 
      0,   0,   0,   0,   0,   0, 
     95,   0,   0,   2,  50,   0, 
      2,   0, 104,   0,   0,   2, 
      1,   0,   0,   0, 155,   0, 
      0,   4,   8,   0,   0,   0, 
      8,   0,   0,   0,   1,   0, 
      0,   0,  80,   0,   0,   8, 
     50,   0,  16,   0,   0,   0, 
      0,   0,  70,   0,   2,   0, 
     70, 128,  48,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,  60,   0, 
      0,   7,  18,   0,  16,   0, 
      0,   0,   0,   0,  26,   0, 
     16,   0,   0,   0,   0,   0, 
     10,   0,  16,   0,   0,   0, 
      0,   0,  31,   0,   4,   3, 
     10,   0,  16,   0,   0,   0, 
      0,   0,  62,   0,   0,   1, 
     21,   0,   0,   1, 163,   0, 
      0,   7, 242,   0,  16,   0, 
      0,   0,   0,   0,  70,   5, 
      2,   0,  70, 238,  33,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,  54,  32,   0,   5, 
    130,   0,  16,   0,   0,   0, 
      0,   0,  58,   0,  16,   0, 
      0,   0,   0,   0, 164,   0, 
      0,   7, 242, 224,  33,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,  70,   5,   2,   0, 
     70,  14,  16,   0,   0,   0, 
      0,   0,  62,   0,   0,   1, 
     83,  70,  73,  48,   8,   0, 
      0,   0,   0,   8,   0,   0, 
      0,   0,   0,   0
};
